name: Greet Everyone
# This workflow is triggered on pushes to the repository.
on: [push]

jobs:
  build:
    # Job name is Greeting
    name: Greeting
    # This job runs on Linux
    runs-on: ubuntu-latest
    steps:
      - name: Hello world
        run: echo こんにちは、世界。
      - name: お宝つくるよ
        run: echo こんにちは、世界だよ。 > hello_world.txt
      - name: お宝隠すよ
        uses: actions/upload-artifact@v1
        with:
          name: hello_world.txt
          path: hello_world.txt

